alpha: 0.0015
map:
  batch_size: 64
  epochs: 500
  lr: 0.01
  seed: 127831678242
ip:
  m: 100
  batch_size: 128
  epochs: 50
  lr: 0.008
  mc_samples: 5
  seed: 4231553
  st_samples: 512
  slq_samples: 1
  slq_num_matvecs: 90
  