model:
  name:                  classifier
  type:                  classifier
  num_h:                 8
  num_l:                 3
  num_c:                 2
  seed:                  12345

optimization:
  full_set_size:         450
  alpha:                 0.005

  map:
    batch_size:          32
    epochs:              250
    lr:                  0.001
    seed:                127831678241

  ip:
    m:                   32
    batch_size:          128

    epochs:              500
    lr:                  0.03
    seed:                1234

    # Used for visualization MC
    mc_samples:          1000

    # Fraction of Z used per substep when masking
    ip_batch_frac:       1.00

    # Stochastic-trace and SLQ settings
    st_samples:          250
    slq_samples:         1
    slq_num_matvecs:     40

    # Optional: interleaved alpha tuning
    alpha_steps_every:   10
    alpha_steps_burnin:  20
    alpha_steps_per_call: 0
