alpha: 0.005
map:
  batch_size: 32
  epochs_map: 250
  lr_map: 0.005
  seed: 127831678241
inducing:
  m_induc: 90
  batch_size: 128
  epochs_induc: 200
  lr_induc: 0.01
  mc_samples: 5
  seed: 4231551
