map:
  batch_size: 32
  epochs_map: 2000
  lr_map: 0.001
  alpha: 0.5
  seed: 127831678241
inducing:
  m_induc: 30
  epochs_induc: 200
  lr_induc: 0.01
  alpha: 0.5
  mc_samples: 10
  seed: 3141592650