model:
  name: LeNet5
  type: classifier
  seed: 123123123
optimization:
  alpha: 0.01
  full_set_size: 60_000
  map:
    lr:         0.00025
    seed:       32132132
    batch_size: 256
    epochs: 100
  ip:
    m:               32
    lr:              0.05
    seed:            280300
    epochs:          500
    batch_size:      256
    mc_samples:      100
    st_samples:      128
    slq_samples:     64
    slq_num_matvecs: 32
sampling: todo