model:
  name:                  LeNet5
  type:                  classifier
  seed:                  123123123
optimization:
  alpha:                 0.005
  full_set_size:         60_000
  map:
    batch_size:          256
    epochs:              50
    lr:                  0.005
    seed:                32132132
  ip:
    m:                   300
    lr:                  0.0005
    seed:                280300
    epochs:              500
    batch_size:          256
    mc_samples:          100
    st_samples:          300
    slq_samples:         -1
    slq_num_matvecs:     -1
sampling:
    mc_samples:          100
    invsqrt_num_matvecs: 128