model:
  name:                  MiniCNN
  type:                  classifier
  seed:                  1337_420
  # MiniCNN-specific
  c1:                    16
  c2:                    32
  num_classes:           10
  checkpoint:            false

optimization:
  alpha:                 0.0005
  full_set_size:         58_800
  map:
    lr:                  0.001
    seed:                32132132
    epochs:              500
    batch_size:          128
  ip:
    m:                   200
    lr:                  0.008
    seed:                280300
    epochs:              250
    batch_size:          128
    mc_samples:          200
    st_samples:          256
    slq_samples:         1
    slq_num_matvecs:     200

sampling:
  mc_samples:            100
  invsqrt_num_matvecs:   128
