model:
  name:                  ResNet1
  type:                  classifier
  num_c:                 10
  seed:                  1231231234
optimization:
  alpha:                 0.005
  full_set_size:         49_000
  map:
    lr:                  0.001
    seed:                32132132
    epochs:              250
    batch_size:          256
  ip:
    m:                   100
    lr:                  0.008
    seed:                280300
    epochs:              100
    batch_size:          256
    mc_samples:          200
    st_samples:          100
    slq_samples:         1
    slq_num_matvecs:     100
sampling:
    mc_samples:          100
    invsqrt_num_matvecs: 128