model:
  name:                  ResNet1
  type:                  classifier
  num_c:                 10
  seed:                  1231231234
optimization:
  alpha:                 0.005 # 0.01 # 0.005
  full_set_size:         49_000
  map:
    lr:                  0.005
    seed:                32132132
    epochs:              75
    batch_size:          256
  ip:
    m:                   100
    lr:                  0.005
    seed:                280300
    epochs:              90
    batch_size:          32
    mc_samples:          200
    st_samples:          24
    slq_samples:         1
    slq_num_matvecs:     16
sampling:
    mc_samples:          100
    invsqrt_num_matvecs: 128